

String indiJSON = "{"
"    \"MAIN\": {"
"        \"SwitchVector\": ["
"            {"
"                \"name\": \"CONNECTION\","
"                \"label\": \"Connection\","
"                \"Switches\": ["
"                    {"
"                        \"name\": \"CONNECT\","
"                        \"label\": \"Connect\","
"                        \"value\": \"On\""
"                    },"
"                    {"
"                        \"name\": \"DISCONNECT\","
"                        \"label\": \"Disconnect\","
"                        \"value\": \"Off\""
"                    }"
"                ]"
"            },"
"            {"
"                \"name\": \"ON_COORD_SET\","
"                \"label\": \"On Set\","
"                \"Switches\": ["
"                    {"
"                        \"name\": \"TRACK\","
"                        \"label\": \"Track\","
"                        \"value\": \"On\""
"                    },"
"                    {"
"                        \"name\": \"SLEW\","
"                        \"label\": \"Slew\","
"                        \"value\": \"Off\""
"                    },"
"                    {"
"                        \"name\": \"SYNC\","
"                        \"label\": \"Sync\","
"                        \"value\": \"Off\""
"                    }"
"                ]"
"            }"
"        ],"
"        \"NumberVector\": [],"
"        \"TextVector\": []"
"    },"
"    \"Connection\": {"
"        \"SwitchVector\": [],"
"        \"NumberVector\": ["
"            {"
"            \"name\": \"EQUATORIAL_EOD_COORD\","
"            \"label\": \"Telescope Coordinates\","
"            \"numbers\": ["
"            {"
"                \"name\": \"RA\","
"                \"label\": \"RA\","
"                \"value\": \"0\""
"            },"
"            {"
"                \"name\": \"DEC\","
"                \"label\": \"DEC\","
"                \"value\": \"0\""
"            }"
"            ]"
"            },"
"            {"
"            \"name\": \"TARGET_EOD_COORD\","
"            \"label\": \"Target Coordinates\","
"            \"numbers\": ["
"            {"
"                \"name\": \"RA\","
"                \"label\": \"RA\","
"                \"value\": \"0\""
"            },"
"            {"
"                \"name\": \"DEC\","
"                \"label\": \"DEC\","
"                \"value\": \"0\""
"            }"
"            ]"
"            },"
"            {"
"            \"name\": \"GEOGRAPHIC_COORD\","
"            \"label\": \"Telescope Location\","
"            \"numbers\": ["
"            {"
"                \"name\": \"LAT\","
"                \"label\": \"Lat\","
"                \"value\": \"34.73166666\""
"            },"
"            {"
"                \"name\": \"LONG\","
"                \"label\": \"Lon\","
"                \"value\": \"273.413333333\""
"            },"
"            {"
"                \"name\": \"ELEV\","
"                \"label\": \"Elev\","
"                \"value\": \"193.52\""
"            }"
"            ]"
"            }"
"            ],"
"        \"TextVector\": ["
"            {"
"                \"name\": \"DRIVER_INFO\","
"                \"label\": \"DriverInfo\","
"                \"texts\": ["
"                    {"
"                        \"name\": \"DRIVER_NAME\","
"                        \"label\": \"Name\","
"                        \"value\": \"ESP32INDI\""
"                    },"
"                    {"
"                        \"name\": \"DRIVER_EXEC\","
"                        \"label\": \"Exec\","
"                        \"value\": \"ESP32 INDI Telescope Simulator\""
"                    },"
"                    {"
"                        \"name\": \"DRIVER_VERSION\","
"                        \"label\": \"Version\","
"                        \"value\": \"1.0\""
"                    },"
"                    {"
"                        \"name\": \"DRIVER_INTERFACE\","
"                        \"label\": \"Interface\","
"                        \"value\": \"5\""
"                    }"
"                ]"
"            }"
"        ]"
"    }"
"}";